version: "3"

services:
  application_db:
    image: postgres:latest
    container_name: application_db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - application_database:/var/lib/postgresql/data/

  application_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: >
      sh -c "python -m manage migrate && python -m manage collectstatic && 
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    image: application:latest
    container_name: application_api
    depends_on:
      - application_db
    restart: on-failure
    ports:
      - "9050:8000"

volumes:
  application_database: